# Generated by Django 2.2.1 on 2019-08-08 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymodel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='UploadFiles',
        ),
    ]
