# Generated by Django 2.2.1 on 2019-08-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymodel', '0002_auto_20190808_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('file', models.FileField(null=True, upload_to='files/%Y/%m/%d', verbose_name='')),
            ],
        ),
        migrations.DeleteModel(
            name='UploadFiles',
        ),
    ]
