# Generated by Django 2.2.1 on 2019-08-08 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymodel', '0003_auto_20190808_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='name',
        ),
    ]
