# Generated by Django 2.2.1 on 2019-08-09 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymodel', '0005_auto_20190808_2209'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
